import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy, provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { LOCALE_ID, enableProdMode } from '@angular/core';
import localeIt from '@angular/common/locales/it';
import { registerLocaleData } from '@angular/common';
import { AppComponent } from './app/app.component';
import { routes } from './app/app.routes';
import { addIcons } from 'ionicons';

registerLocaleData(localeIt);

import {
  mailOutline, lockClosedOutline, personAddOutline, arrowBackOutline,
  personOutline, person, checkboxOutline, eyeOutline, eyeOffOutline,
  homeOutline, calendarOutline, peopleOutline, people, searchOutline,
  notificationsOutline, sparklesOutline, checkmarkCircleOutline, checkmarkCircle,
  add, addCircleOutline, addCircle,
  trashOutline, notificationsOffOutline, shieldCheckmarkOutline,
  logOutOutline, cameraOutline, camera,
  chatboxEllipsesOutline, schoolOutline, school,
  arrowForwardOutline, chevronForward, bookmark, ellipse, magnet,
  codeSlash, language, triangle, flash, cloudUploadOutline,
  settingsOutline, bookmarkOutline, gridOutline, shareSocialOutline,
  pencilOutline, statsChartOutline, search, desktopOutline,
  cloudDownloadOutline, documentText, calculator, hardwareChip,
  arrowBack, chevronBack, ellipsisHorizontal, send,
  addOutline, folderOpenOutline, briefcaseOutline, downloadOutline,
  image, document, close,
  arrowForward, timeOutline,
  documentTextOutline, ellipseOutline, pauseCircle, playCircle,
  refreshOutline, closeOutline, trophyOutline, flameOutline,
  listOutline, optionsOutline, chevronDown, warningOutline,
  checkmarkDoneOutline, calendarClearOutline, contrastOutline,
  alertCircleOutline,
} from 'ionicons/icons';

addIcons({
  'mail-outline': mailOutline,
  'lock-closed-outline': lockClosedOutline,
  'person-add-outline': personAddOutline,
  'arrow-back-outline': arrowBackOutline,
  'person-outline': personOutline,
  'person': person,
  'checkbox-outline': checkboxOutline,
  'eye-outline': eyeOutline,
  'eye-off-outline': eyeOffOutline,
  'home-outline': homeOutline,
  'calendar-outline': calendarOutline,
  'people-outline': peopleOutline,
  'people': people,
  'search-outline': searchOutline,
  'notifications-outline': notificationsOutline,
  'sparkles-outline': sparklesOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'checkmark-circle': checkmarkCircle,
  'add': add,
  'add-circle-outline': addCircleOutline,
  'add-circle': addCircle,
  'trash-outline': trashOutline,
  'trash': trashOutline,
  'notifications-off-outline': notificationsOffOutline,
  'notifications-off': notificationsOffOutline,
  'shield-checkmark-outline': shieldCheckmarkOutline,
  'log-out-outline': logOutOutline,
  'camera-outline': cameraOutline,
  'camera': camera,
  'chatbox-ellipses-outline': chatboxEllipsesOutline,
  'school-outline': schoolOutline,
  'school': school,
  'arrow-forward-outline': arrowForwardOutline,
  'chevron-forward': chevronForward,
  'bookmark': bookmark,
  'ellipse': ellipse,
  'magnet': magnet,
  'code-slash': codeSlash,
  'language': language,
  'triangle': triangle,
  'flash': flash,
  'cloud-upload-outline': cloudUploadOutline,
  'settings-outline': settingsOutline,
  'bookmark-outline': bookmarkOutline,
  'grid-outline': gridOutline,
  'share-social-outline': shareSocialOutline,
  'pencil-outline': pencilOutline,
  'stats-chart-outline': statsChartOutline,
  'search': search,
  'desktop-outline': desktopOutline,
  'cloud-download-outline': cloudDownloadOutline,
  'document-text': documentText,
  'calculator': calculator,
  'hardwareChip': hardwareChip,
  'arrow-back': arrowBack,
  'chevron-back': chevronBack,
  'ellipsis-horizontal': ellipsisHorizontal,
  'send': send,
  'add-outline': addOutline,
  'folder-open-outline': folderOpenOutline,
  'briefcase-outline': briefcaseOutline,
  'download-outline': downloadOutline,
  'image': image,
  'document': document,
  'close': close,
  'arrow-forward': arrowForward,
  'time-outline': timeOutline,
  'document-text-outline': documentTextOutline,
  'ellipse-outline': ellipseOutline,
  'pause-circle': pauseCircle,
  'play-circle': playCircle,
  'refresh-outline': refreshOutline,
  'close-outline': closeOutline,
  'trophy-outline': trophyOutline,
  'flame-outline': flameOutline,
  'list-outline': listOutline,
  'options-outline': optionsOutline,
  'chevron-down': chevronDown,
  'warning-outline': warningOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
  'calendar-clear-outline': calendarClearOutline,
  'contrast-outline': contrastOutline,
  'alertCircleOutline,': alertCircleOutline,
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular({ mode: 'ios' }),
    provideRouter(routes),
    provideHttpClient(),
    { provide: LOCALE_ID, useValue: 'it-IT' }
  ],
});